name: WordPress Secu

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  wpscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start WordPress stack
        run: |
          docker compose -f docker/docker-compose.yml up -d

      - name: Wait for WordPress to be fully ready
        run: |
          echo "Waiting for WordPress..."

          for i in {1..60}; do
            STATUS=$(curl -sL -w "%{http_code}" -o /dev/null http://localhost:8080 || true)
            if [ "$STATUS" = "200" ]; then
              echo "WordPress is READY"
              exit 0
            fi
            sleep 5
          done

          echo "WordPress did not start properly"
          docker ps
          docker compose -f docker/docker-compose.yml logs
          exit 1

      - name: Initialize WordPress installation
        run: |
          echo "Initializing WordPress site configuration..."

          curl -s -X POST \
            -d "weblog_title=CI-Security-Test" \
            -d "user_name=admin" \
            -d "admin_password=bIE5QDgtN0VDx2fd2Kx*3X12vf" \
            -d "admin_password2=bIE5QDgtN0VDx2fd2Kx*3X12vf" \
            -d "admin_email=ci-project@gmail.com" \
            -d "blog_public=1" \
            -d "Submit=Install WordPress" \
            "http://localhost:8080/wp-admin/install.php?step=2"

          echo "WordPress installation completed."
      - name: Allow extra boot time (stabilisation CI)
        run: sleep 20

      - name: Run WPScan
        run: |
          mkdir -p scans

          docker run --rm --network host wpscanteam/wpscan \
            --url http://localhost:8080 \
            --enumerate u,vp,vt \
            --format cli \
            --no-update \
            | tee scans/wpscan.txt

      - name: Upload WPScan report
        uses: actions/upload-artifact@v4
        with:
          name: wpscan-report
          path: scans/

      - name: Stop containers
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down
